"""Generate ``packaging/version_info.txt`` (PyInstaller ``VSVersionInfo`` text) from the package version.

Build step (3) of ``build.py``: the version is read from ``glasstranslate/__init__.py``
(``__version__ = "x.y.z"``) without importing the package, so the build never pulls Qt or the
engine stack into the build process.  The output format is the one verified in
``demo/output/probes/packaging/app/version_info.txt`` (RT_VERSION resource with
FileDescription / ProductVersion visible in Explorer's Details tab).

Usage::

    python packaging/make_version_info.py            # writes packaging/version_info.txt
    python packaging/make_version_info.py --version 0.2.0 --out build/vi.txt
"""
from __future__ import annotations

import argparse
import logging
import re
import sys
from pathlib import Path
from typing import Optional, Tuple

log = logging.getLogger(__name__)

PACKAGING_DIR = Path(__file__).resolve().parent
ROOT = PACKAGING_DIR.parent
INIT_FILE = ROOT / "glasstranslate" / "__init__.py"
DEFAULT_OUT = PACKAGING_DIR / "version_info.txt"

PRODUCT_NAME = "GlassTranslate"
COMPANY_NAME = "GlassTranslate"
FILE_DESCRIPTION = "GlassTranslate - live screen translation overlay"
LEGAL_COPYRIGHT = "MIT"
EXE_NAME = "GlassTranslate.exe"

_VERSION_RE = re.compile(r"^__version__\s*=\s*['\"]([^'\"]+)['\"]", re.M)


def read_package_version(init_file: Path = INIT_FILE) -> Optional[str]:
    """Return ``__version__`` from ``glasstranslate/__init__.py`` or ``None`` when absent."""
    try:
        text = init_file.read_text(encoding="utf-8")
    except OSError:
        return None
    m = _VERSION_RE.search(text)
    return m.group(1).strip() if m else None


def version_tuple(version: str) -> Tuple[int, int, int, int]:
    """``"0.2.0"`` -> ``(0, 2, 0, 0)``; non-numeric suffixes (``0.2.0rc1``) are ignored."""
    parts = []
    for piece in version.split("."):
        m = re.match(r"\d+", piece)
        if not m:
            break
        parts.append(int(m.group(0)))
        if len(parts) == 4:
            break
    while len(parts) < 4:
        parts.append(0)
    return parts[0], parts[1], parts[2], parts[3]


def render_version_info(version: str, exe_name: str = EXE_NAME) -> str:
    """Return the ``VSVersionInfo`` literal for *version* (``filevers``/``prodvers`` 4-tuples)."""
    vt = version_tuple(version)
    dotted = ".".join(str(v) for v in vt)
    internal = exe_name[:-4] if exe_name.lower().endswith(".exe") else exe_name
    return f"""# UTF-8
# Generated by packaging/make_version_info.py from glasstranslate.__version__ = {version!r}.
# Consumed by PyInstaller: EXE(version="packaging/version_info.txt").  Do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vt!r},
    prodvers={vt!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u"040904B0",
        [StringStruct(u"CompanyName", u"{COMPANY_NAME}"),
         StringStruct(u"FileDescription", u"{FILE_DESCRIPTION}"),
         StringStruct(u"FileVersion", u"{dotted}"),
         StringStruct(u"InternalName", u"{internal}"),
         StringStruct(u"LegalCopyright", u"{LEGAL_COPYRIGHT}"),
         StringStruct(u"OriginalFilename", u"{exe_name}"),
         StringStruct(u"ProductName", u"{PRODUCT_NAME}"),
         StringStruct(u"ProductVersion", u"{version}")])
    ]),
    VarFileInfo([VarStruct(u"Translation", [1033, 1200])])
  ]
)
"""


def write_version_info(version: str, out: Path = DEFAULT_OUT, exe_name: str = EXE_NAME) -> Path:
    """Write the version resource text for *version* to *out* and return the path."""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_version_info(version, exe_name), encoding="utf-8")
    log.info("version_info: %s -> %s", version, out)
    return out


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--version", help="override the version (default: glasstranslate.__version__)")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output file")
    parser.add_argument("--exe-name", default=EXE_NAME, help="OriginalFilename (default GlassTranslate.exe)")
    parser.add_argument(
        "--fallback",
        help="version to use when glasstranslate.__version__ is missing (default: fail)",
    )
    args = parser.parse_args(argv)
    logging.basicConfig(level="INFO", format="%(levelname)s %(name)s: %(message)s")

    version = args.version or read_package_version()
    if version is None:
        if args.fallback is None:
            log.error("glasstranslate/__init__.py has no __version__ and no --fallback was given")
            return 1
        log.warning("glasstranslate.__version__ missing; using fallback %s", args.fallback)
        version = args.fallback
    write_version_info(version, args.out, args.exe_name)
    print(f"version_info: {version} -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
