"""Settings / status window: the Liquid Glass control panel.

:class:`ControlWindow` is a frameless, per-pixel-translucent ``QQuickView`` that loads
``qrc:/qml/Main.qml`` and exposes two context properties to it: ``bridge``
(:class:`ControlBridge` - every setting, list, state flag and action of the panel) and
``appearance`` (:class:`~glasstranslate.ui.glass.appearance.Appearance` - Windows
transparency / reduced motion / high contrast / dark mode / text scale).  The public Python
contract is unchanged from the old QWidget window so ``app.py`` keeps working: signals
``config_changed(AppConfig)``, ``start_stop_requested(bool)``, ``grab_mode_requested()``,
``toggle_glass_requested()``, ``models_changed()``, ``closed()``; methods ``show()``,
``load_config()``, ``set_running()``, ``update_stats()``, ``show_status()``, ``save_soon()``,
``save_now()`` and the ``config`` property.  Edits made from QML mutate the
:class:`~glasstranslate.config.settings.AppConfig`, emit ``config_changed`` and persist with a
300 ms debounce.

What the glass refracts (docs/GLASS_DESIGN.md section 1.2): while the window is visible, not
minimised and glass is allowed, a :class:`~glasstranslate.ui.glass.backdrop.BackdropGrabber`
thread copies the desktop pixels behind the window at 15 Hz (the window itself is excluded
from capture with ``SetWindowDisplayAffinity``); the GUI thread stores each frame in the
``image://backdrop/<serial>`` provider and updates ``bridge.backdropSerial`` /
``backdropOrigin`` / ``backdropLuma`` / ``inkPolarity``.

Qt resources: this module imports the compiled ``resources_rc``; in a source checkout without
it (the file is generated, see ``tools/build_resources.py``) it builds the resources once.
"""
from __future__ import annotations

import importlib
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

from PySide6.QtCore import (
    Property,
    QObject,
    QPointF,
    QSize,
    QSizeF,
    QTimer,
    QUrl,
    Qt,
    Signal,
    Slot,
)
from PySide6.QtGui import (
    QCloseEvent,
    QDesktopServices,
    QExposeEvent,
    QFontDatabase,
    QHideEvent,
    QIcon,
    QMoveEvent,
    QResizeEvent,
    QScreen,
    QShowEvent,
    QWindow,
)
from PySide6.QtQuick import QQuickItem, QQuickView

from ..config.settings import AppConfig, project_root, user_data_dir
from ..core.types import PipelineStats
from .glass import profile, win32
from .glass.appearance import Appearance
from .glass.backdrop import BackdropFrame, BackdropGrabber, BackdropProvider, InkPolarity, LumaSmoother, WindowGeometry
from .hotkeys import normalize_hotkey
from .bridge_fields import (  # noqa: F401 - re-exported for tests and app.py
    _CONFIG_FIELDS,
    _ONLINE_BACKENDS,
    _OCR_DEVICES,
    _TRANSLATE_DEVICES,
    _TRANSLATE_DEVICES_FROZEN,
    CUDA_FROZEN_HINT,
    LANGUAGES,
    _cfg_get,
    _cfg_set,
    _config_property,
    _items,
    download_label,
    download_progress,
    format_stats,
    is_frozen,
    translate_device_items,
)
from .download_workers import MangaOcrDownloadWorker, ModelDownloadWorker  # noqa: F401 - re-exported
from .stats_model import StatsModel

__all__ = [
    "CUDA_FROZEN_HINT",
    "LANGUAGES",
    "MAIN_QML_URL",
    "WINDOW_TITLE",
    "ControlBridge",
    "ControlWindow",
    "ModelDownloadWorker",
    "StatsModel",
    "download_label",
    "download_progress",
    "format_stats",
    "is_frozen",
    "translate_device_items",
]

log = logging.getLogger(__name__)

_SAVE_DEBOUNCE_MS = 300
WINDOW_TITLE = "GlassTranslate"
MAIN_QML_URL = "qrc:/qml/Main.qml"
WINDOW_DEFAULT_SIZE = QSize(832, 640)  # slab 760x560 inside the 36/28/36/52 shadow margin; fixed-size, not resizable
WINDOW_FLAGS = (
    Qt.WindowType.Window
    | Qt.WindowType.FramelessWindowHint
    | Qt.WindowType.WindowMinimizeButtonHint
    | Qt.WindowType.WindowSystemMenuHint
)
# setHotkey(which, ...) accepts the short key, the bridge property name or the config field.
_HOTKEY_FIELDS: Dict[str, str] = {
    "grab": "toggle_grab",
    "running": "toggle_running",
    "hidden": "toggle_hidden",
    "hotkeyGrab": "toggle_grab",
    "hotkeyRunning": "toggle_running",
    "hotkeyHidden": "toggle_hidden",
    "toggle_grab": "toggle_grab",
    "toggle_running": "toggle_running",
    "toggle_hidden": "toggle_hidden",
}
_HOTKEY_PROPS: Dict[str, str] = {"toggle_grab": "hotkeyGrab", "toggle_running": "hotkeyRunning", "toggle_hidden": "hotkeyHidden"}


# ------------------------------------------------------------------------------- resources
def _ensure_resources() -> bool:
    """Import the compiled Qt resources (``:/qml``, ``:/fonts``, ``:/icons``).

    ``resources_rc.py`` is generated by ``tools/build_resources.py`` and not committed during
    development; in a source checkout it is built once here when missing, and rebuilt when
    present but stale (its digest no longer matches its QML/shader/font inputs) so an outdated
    file left over from before a redesign can never be served silently.  The frozen exe must ship
    a fresh one; there is no ``tools/`` there to rebuild from.
    """
    try:
        module = importlib.import_module("glasstranslate.ui.resources_rc")
        imported = True
    except ImportError:
        module = None
        imported = False

    if is_frozen():
        if imported:
            return True
        log.error("resources_rc is missing from the frozen bundle; QML, fonts and icon are unavailable")
        return False

    root = str(project_root())
    if root not in sys.path:
        sys.path.insert(0, root)
    try:
        from tools.build_resources import build, check_digest  # noqa: WPS433 - dev-only dependency
    except ImportError:
        # pip-installed layout without tools/: nothing to rebuild from, fall back to the import result.
        return imported

    if imported and check_digest()[0]:
        return True
    if imported:
        log.warning("resources_rc.py is stale (inputs changed since it was generated); rebuilding")
    try:
        out = build()
        importlib.invalidate_caches()
        if imported:
            # Unregister the old byte buffers before reload overwrites the module
            # globals that keep them alive; Qt would otherwise hold dangling data.
            module.qCleanupResources()
            importlib.reload(module)
        else:
            importlib.import_module("glasstranslate.ui.resources_rc")
        log.info("built Qt resources: %s", out)
        return True
    except Exception:
        log.exception("building the Qt resources failed; the control window cannot load its QML")
        return False


RESOURCES_OK = _ensure_resources()


# ------------------------------------------------------------------------------------ bridge
class ControlBridge(QObject):
    """Everything ``Main.qml`` reads and calls (context property ``bridge``).

    Config properties are read/write: a set coerces the value, mutates the ``AppConfig``, emits
    the property's notify signal and ``config_changed(cfg)`` and restarts the 300 ms save timer;
    sets are ignored while :meth:`load_config` runs and when the value is unchanged.  Lists are
    ``{value, text}`` entries (an unknown current value is appended).  State (running, status,
    stats, download row, backdrop, ink polarity) is read-only from QML and driven from Python.
    ``window`` (the :class:`ControlWindow`) is optional so the bridge can be tested headless.
    """

    # -- to the application (relayed by ControlWindow)
    config_changed = Signal(object)  # AppConfig
    start_stop_requested = Signal(bool)  # True = start
    grab_mode_requested = Signal()
    toggle_glass_requested = Signal()
    capture_mode_requested = Signal(bool)  # overlay capture mode on/off (runtime only, F1)
    models_changed = Signal()  # a package was downloaded

    # -- QML notifies
    sourceLangChanged = Signal()
    targetLangChanged = Signal()
    ocrEngineChanged = Signal()
    ocrDeviceChanged = Signal()
    translationBackendChanged = Signal()
    translateDeviceChanged = Signal()
    apiUrlChanged = Signal()
    apiKeyChanged = Signal()
    modelsDirChanged = Signal()
    overlayOpacityChanged = Signal()
    fontFamilyChanged = Signal()
    hideOriginalChanged = Signal()
    mangaModeChanged = Signal()
    uppercaseChanged = Signal()
    refreshHzChanged = Signal()
    debounceMsChanged = Signal()
    minConfidenceChanged = Signal()
    hotkeyGrabChanged = Signal()
    hotkeyRunningChanged = Signal()
    hotkeyHiddenChanged = Signal()
    geminiModelChanged = Signal()
    geminiApiFormatChanged = Signal()
    geminiBaseUrlChanged = Signal()
    geminiTimeoutSChanged = Signal()
    geminiMaxRetriesChanged = Signal()
    geminiApiKeyChanged = Signal()  # set/not-set only; the key itself never crosses the bridge
    seriesNameChanged = Signal()
    seriesPromptTemplateChanged = Signal()
    listsChanged = Signal()
    backendFlagsChanged = Signal()
    loadingChanged = Signal()
    runningChanged = Signal()
    overlayCaptureModeChanged = Signal()
    statusMessageChanged = Signal()
    downloadChanged = Signal()
    backdropChanged = Signal()
    backdropShiftChanged = Signal()
    inkPolarityChanged = Signal()

    def __init__(
        self,
        cfg: AppConfig,
        config_path: Optional[Path] = None,
        *,
        window: Optional[QWindow] = None,
        appearance: Optional[Appearance] = None,
        parent: Optional[QObject] = None,
    ) -> None:
        super().__init__(parent)
        from ..ocr.factory import available_engines
        from ..translate.factory import available_backends

        self._cfg = cfg
        self._config_path = config_path
        self._window = window
        self._appearance = appearance
        self._loading = False
        self._running = False
        self._capture_mode = False  # runtime only: never read from / written to AppConfig
        self._status = "Ready"
        self.status_history: List[str] = []
        self._stats = StatsModel(self)
        self._engines: List[str] = list(available_engines())
        self._backends: List[str] = list(available_backends())
        self._families: Optional[List[str]] = None
        # download row
        self._download_worker: Optional[ModelDownloadWorker] = None
        self._download_visible = False
        self._download_label = ""
        self._download_progress = -1
        self._download_base_label = ""
        # backdrop
        self._backdrop_serial = 0
        self._backdrop_origin = QPointF(0.0, 0.0)
        self._backdrop_size = QSizeF(0.0, 0.0)
        # F2-1: physical origin of the window the current frame was grabbed for, and of the
        # window now (None until the first moveEvent).  Their difference is backdropShift.
        self._frame_window_origin: Tuple[int, int] = (0, 0)
        self._window_origin: Optional[Tuple[int, int]] = None
        self._backdrop_dpr = 1.0
        self._backdrop_shift = QPointF(0.0, 0.0)
        self._luma = LumaSmoother()
        self._polarity = InkPolarity(self._dark_mode())
        # persistence
        self._save_timer = QTimer(self)
        self._save_timer.setSingleShot(True)
        self._save_timer.setInterval(_SAVE_DEBOUNCE_MS)
        self._save_timer.timeout.connect(self.save_now)
        if appearance is not None:
            appearance.changed.connect(self.appearance_changed)

    # ------------------------------------------------------------------ python API
    @property
    def config(self) -> AppConfig:
        return self._cfg

    @property
    def window(self) -> Optional[QWindow]:
        return self._window

    def load_config(self, cfg: AppConfig) -> None:
        """Adopt ``cfg`` and refresh every binding without emitting ``config_changed``."""
        self._cfg = cfg
        self._loading = True
        self.loadingChanged.emit()
        try:
            for name in _CONFIG_FIELDS:
                getattr(self, name + "Changed").emit()
            self.listsChanged.emit()
            self.backendFlagsChanged.emit()
        finally:
            self._loading = False
            self.loadingChanged.emit()

    def set_running(self, running: bool) -> None:
        running = bool(running)
        if running != self._running:
            self._running = running
            self.runningChanged.emit()

    def show_status(self, message: str) -> None:
        """Set the status-strip message (kept in ``status_history`` for the smoke report)."""
        message = str(message)
        self.status_history.append(message)
        if message != self._status:
            self._status = message
            self.statusMessageChanged.emit()
        else:
            self.statusMessageChanged.emit()  # the same text again still refreshes the strip

    def save_soon(self) -> None:
        """Schedule a debounced save (changes made outside the window, e.g. the glass geometry)."""
        self._save_timer.start()

    @Slot()
    def save_now(self) -> None:
        """Persist the config immediately (normally driven by the debounce timer)."""
        self._save_timer.stop()
        try:
            self._cfg.save(self._config_path)
        except Exception as exc:
            log.exception("saving config failed")
            self.show_status(f"Could not save config: {exc}")

    def flush_pending_save(self) -> None:
        if self._save_timer.isActive():
            self.save_now()

    def push_backdrop(self, frame: BackdropFrame) -> None:
        """GUI-thread entry for a grabbed frame: serial, origin, smoothed luma, polarity."""
        ox, oy = frame.origin_logical
        self._backdrop_serial += 1
        self._backdrop_origin = QPointF(ox, oy)
        dpr = frame.dpr if frame.dpr > 0 else 1.0
        self._backdrop_dpr = dpr
        self._backdrop_size = QSizeF(frame.image.width() / dpr, frame.image.height() / dpr)
        self._frame_window_origin = (frame.window_rect.x, frame.window_rect.y)
        self._luma.update(frame.luma, frame.timestamp)
        self.backdropChanged.emit()
        self._update_backdrop_shift()
        if self._glass_mode() and self._polarity.update(self._backdrop_luma()):
            self.inkPolarityChanged.emit()

    def set_window_origin(self, x: int, y: int) -> None:
        """GUI-thread entry from ``moveEvent``: physical top-left of the window right now."""
        self._window_origin = (int(x), int(y))
        self._update_backdrop_shift()

    def _update_backdrop_shift(self) -> None:
        """Logical offset that keeps a frame grabbed for an older window rect desktop-aligned."""
        if self._window_origin is None or self._backdrop_serial == 0:
            shift = QPointF(0.0, 0.0)
        else:
            fx, fy = self._frame_window_origin
            wx, wy = self._window_origin
            shift = QPointF((fx - wx) / self._backdrop_dpr, (fy - wy) / self._backdrop_dpr)
        if shift != self._backdrop_shift:
            self._backdrop_shift = shift
            self.backdropShiftChanged.emit()

    @Slot()
    def appearance_changed(self) -> None:
        """Outside glass mode (or before the first frame) the polarity follows the system theme."""
        if not self._glass_mode() or self._backdrop_serial == 0:
            if self._polarity.reset(self._dark_mode()):
                self.inkPolarityChanged.emit()

    # ------------------------------------------------------------------- internals
    def _dark_mode(self) -> bool:
        return bool(self._appearance.darkMode) if self._appearance is not None else False

    def _glass_mode(self) -> bool:
        return bool(self._appearance.glassAllowed) if self._appearance is not None else True

    def _backdrop_luma(self) -> float:
        return float(self._luma.value) if self._luma.value is not None else 0.5

    def _config_edited(self) -> None:
        self.config_changed.emit(self._cfg)
        self._save_timer.start()

    def _base_values(self, name: str) -> Optional[Sequence[str]]:
        """Known values of a list-backed property (None for free-form fields)."""
        if name == "sourceLang":
            return ["auto"] + [code for code, _ in LANGUAGES]
        if name == "targetLang":
            return [code for code, _ in LANGUAGES]
        if name == "ocrEngine":
            return self._engines
        if name == "ocrDevice":
            return _OCR_DEVICES
        if name == "translationBackend":
            return self._backends
        if name == "translateDevice":
            return _TRANSLATE_DEVICES_FROZEN if is_frozen() else _TRANSLATE_DEVICES
        if name == "fontFamily":
            return self._font_families_base()
        return None

    def _set_config(self, name: str, value: Any) -> None:
        if self._loading:
            return
        spec = _CONFIG_FIELDS[name]
        try:
            value = spec.coerce(value)
        except (TypeError, ValueError):
            log.warning("ignoring invalid value %r for %s", value, name)
            return
        if name == "modelsDir" and not value:
            value = self._cfg.models_dir  # an empty models dir keeps the previous value
        if _cfg_get(self._cfg, spec.attr) == value:
            return
        _cfg_set(self._cfg, spec.attr, value)
        getattr(self, name + "Changed").emit()
        if name == "translationBackend":
            self.backendFlagsChanged.emit()
        base = self._base_values(name)
        if base is not None and value not in base:
            self.listsChanged.emit()
        self._config_edited()

    def _font_families_base(self) -> List[str]:
        if self._families is None:
            try:
                self._families = [str(f) for f in QFontDatabase.families()]
            except Exception:  # pragma: no cover - no QGuiApplication yet
                self._families = []
        return self._families

    # ------------------------------------------------------------ config properties
    sourceLang = _config_property("sourceLang", str, sourceLangChanged)
    targetLang = _config_property("targetLang", str, targetLangChanged)
    ocrEngine = _config_property("ocrEngine", str, ocrEngineChanged)
    ocrDevice = _config_property("ocrDevice", str, ocrDeviceChanged)
    translationBackend = _config_property("translationBackend", str, translationBackendChanged)
    translateDevice = _config_property("translateDevice", str, translateDeviceChanged)
    apiUrl = _config_property("apiUrl", str, apiUrlChanged)
    apiKey = _config_property("apiKey", str, apiKeyChanged)
    modelsDir = _config_property("modelsDir", str, modelsDirChanged)
    overlayOpacity = _config_property("overlayOpacity", float, overlayOpacityChanged)
    fontFamily = _config_property("fontFamily", str, fontFamilyChanged)
    hideOriginal = _config_property("hideOriginal", bool, hideOriginalChanged)
    mangaMode = _config_property("mangaMode", bool, mangaModeChanged)
    uppercase = _config_property("uppercase", bool, uppercaseChanged)
    refreshHz = _config_property("refreshHz", float, refreshHzChanged)
    debounceMs = _config_property("debounceMs", int, debounceMsChanged)
    minConfidence = _config_property("minConfidence", float, minConfidenceChanged)
    hotkeyGrab = _config_property("hotkeyGrab", str, hotkeyGrabChanged)
    hotkeyRunning = _config_property("hotkeyRunning", str, hotkeyRunningChanged)
    hotkeyHidden = _config_property("hotkeyHidden", str, hotkeyHiddenChanged)
    geminiModel = _config_property("geminiModel", str, geminiModelChanged)
    geminiApiFormat = _config_property("geminiApiFormat", str, geminiApiFormatChanged)
    geminiBaseUrl = _config_property("geminiBaseUrl", str, geminiBaseUrlChanged)
    geminiTimeoutS = _config_property("geminiTimeoutS", float, geminiTimeoutSChanged)
    geminiMaxRetries = _config_property("geminiMaxRetries", int, geminiMaxRetriesChanged)
    seriesName = _config_property("seriesName", str, seriesNameChanged)
    seriesPromptTemplate = _config_property("seriesPromptTemplate", str, seriesPromptTemplateChanged)

    # ------------------------------------------------------------ Gemini API key (secret store)
    def _gemini_api_key_set(self) -> bool:
        from ..config.secrets import has_gemini_api_key

        return has_gemini_api_key()

    def _gemini_api_key_hint(self) -> str:
        from ..config.secrets import GEMINI_API_KEY_ENV, get_gemini_api_key, redact

        if os.environ.get(GEMINI_API_KEY_ENV, "").strip():
            return f"Using the {GEMINI_API_KEY_ENV} environment variable"
        key = get_gemini_api_key()
        return f"Key stored ({redact(key)})" if key else "No key stored"

    geminiApiKeySet = Property(bool, _gemini_api_key_set, notify=geminiApiKeyChanged)
    geminiApiKeyHint = Property(str, _gemini_api_key_hint, notify=geminiApiKeyChanged)

    @Slot(str, result=bool)
    def setGeminiApiKey(self, text: str) -> bool:
        """Store (or, with empty text, clear) the Gemini API key in the user secret store.

        The key never enters ``AppConfig``: it is written to ``secrets.json`` under the user data
        directory and only ``geminiApiKeySet`` / a redacted hint are readable from QML.
        """
        from ..config.secrets import set_gemini_api_key

        try:
            set_gemini_api_key(str(text))
        except OSError as exc:
            log.warning("storing the Gemini API key failed: %s", exc.__class__.__name__)
            self.show_status("Could not store the Gemini API key (see log)")
            return False
        self.geminiApiKeyChanged.emit()
        self.show_status("Gemini API key stored" if str(text).strip() else "Gemini API key cleared")
        # The key lives outside AppConfig, so a config diff can never notice it changed: ask the
        # pipeline to rebuild the translator explicitly (app.py wires this to refresh_models()).
        self.models_changed.emit()
        return True

    @Slot(result=str)
    def defaultPromptTemplate(self) -> str:
        from ..translate.context import DEFAULT_TEMPLATE

        return DEFAULT_TEMPLATE

    @Slot()
    def resetPromptTemplate(self) -> None:
        self._set_config("seriesPromptTemplate", "")

    # ------------------------------------------------------------------------ lists
    def _languages_source(self) -> List[Dict[str, str]]:
        pairs = [("auto", "Auto-detect")] + [(code, f"{name} ({code})") for code, name in LANGUAGES]
        return _items(pairs, self._cfg.source_lang)

    def _languages_target(self) -> List[Dict[str, str]]:
        return _items([(code, f"{name} ({code})") for code, name in LANGUAGES], self._cfg.target_lang)

    def _ocr_engines(self) -> List[Dict[str, str]]:
        from ..ocr.factory import engine_label

        return _items([(n, engine_label(n)) for n in self._engines], self._cfg.ocr_engine)

    def _ocr_devices(self) -> List[Dict[str, str]]:
        return _items([(d, d) for d in _OCR_DEVICES], self._cfg.ocr_device)

    def _backend_items(self) -> List[Dict[str, str]]:
        return _items([(n, n) for n in self._backends], self._cfg.translation_backend)

    def _translate_devices(self) -> List[Dict[str, str]]:
        return translate_device_items(self._cfg.translate_device)

    def _font_families(self) -> List[str]:
        families = list(self._font_families_base())
        if self._cfg.font_family not in families:
            families.append(self._cfg.font_family)
        return families

    languagesSource = Property("QVariantList", _languages_source, notify=listsChanged)
    languagesTarget = Property("QVariantList", _languages_target, notify=listsChanged)
    ocrEngines = Property("QVariantList", _ocr_engines, notify=listsChanged)
    ocrDevices = Property("QVariantList", _ocr_devices, notify=listsChanged)
    backends = Property("QVariantList", _backend_items, notify=listsChanged)
    translateDevices = Property("QVariantList", _translate_devices, notify=listsChanged)
    fontFamilies = Property("QVariantList", _font_families, notify=listsChanged)

    # ----------------------------------------------------------------- derived flags
    def _backend_online(self) -> bool:
        return self._cfg.translation_backend in _ONLINE_BACKENDS

    def _backend_argos(self) -> bool:
        return self._cfg.translation_backend == "argos"

    def _backend_gemini(self) -> bool:
        return self._cfg.translation_backend == "gemini"

    def _backend_libre(self) -> bool:
        return self._cfg.translation_backend == "libretranslate"

    def _gemini_models(self) -> List[Dict[str, str]]:
        from ..translate.gemini import MODEL_PRESETS

        return _items([(m, m) for m in MODEL_PRESETS], self._cfg.gemini_model)

    def _gemini_api_formats(self) -> List[Dict[str, str]]:
        return _items([("native", "Gemini native (x-goog-api-key)"), ("openai", "OpenAI-compatible (Bearer)")],
                      self._cfg.gemini_api_format)

    geminiModels = Property("QVariantList", _gemini_models, notify=listsChanged)
    geminiApiFormats = Property("QVariantList", _gemini_api_formats, notify=listsChanged)

    def _translate_device_hint(self) -> str:
        return CUDA_FROZEN_HINT if is_frozen() and self._cfg.translate_device == "cuda" else ""

    backendOnline = Property(bool, _backend_online, notify=backendFlagsChanged)
    backendArgos = Property(bool, _backend_argos, notify=backendFlagsChanged)
    backendGemini = Property(bool, _backend_gemini, notify=backendFlagsChanged)
    backendLibre = Property(bool, _backend_libre, notify=backendFlagsChanged)
    translateDeviceHint = Property(str, _translate_device_hint, notify=translateDeviceChanged)
    frozen = Property(bool, lambda self: is_frozen(), constant=True)
    loading = Property(bool, lambda self: self._loading, notify=loadingChanged)

    # ------------------------------------------------------------------------ state
    def _set_capture_mode(self, on: bool) -> None:
        on = bool(on)
        if on == self._capture_mode:
            return
        self._capture_mode = on
        self.overlayCaptureModeChanged.emit()
        self.capture_mode_requested.emit(on)

    running = Property(bool, lambda self: self._running, notify=runningChanged)
    overlayCaptureMode = Property(
        bool, lambda self: self._capture_mode, _set_capture_mode, notify=overlayCaptureModeChanged
    )
    statusMessage = Property(str, lambda self: self._status, notify=statusMessageChanged)
    stats = Property(QObject, lambda self: self._stats, constant=True)
    windowTitle = Property(str, lambda self: WINDOW_TITLE, constant=True)

    def _download_active(self) -> bool:
        return self._download_worker is not None and self._download_worker.isRunning()

    downloadActive = Property(bool, _download_active, notify=downloadChanged)
    downloadVisible = Property(bool, lambda self: self._download_visible, notify=downloadChanged)
    downloadLabel = Property(str, lambda self: self._download_label, notify=downloadChanged)
    downloadProgress = Property(int, lambda self: self._download_progress, notify=downloadChanged)

    backdropSerial = Property(int, lambda self: self._backdrop_serial, notify=backdropChanged)
    backdropOrigin = Property(QPointF, lambda self: QPointF(self._backdrop_origin), notify=backdropChanged)
    # F2-1: (frame window origin - current window origin) / dpr.  Main.qml adds it to backdropOrigin
    # so a frame grabbed before the last move is drawn where that desktop content still is.
    backdropShift = Property(QPointF, lambda self: QPointF(self._backdrop_shift), notify=backdropShiftChanged)
    # Logical size of the current backdrop image.  Qt Quick ignores QImage.devicePixelRatio for
    # image-provider images (Image.implicitWidth reports the *physical* width), so Main.qml sizes
    # the backdrop layer from this instead - otherwise the texture is magnified by the DPR at 150 %.
    backdropSize = Property(QSizeF, lambda self: QSizeF(self._backdrop_size), notify=backdropChanged)
    backdropLuma = Property(float, _backdrop_luma, notify=backdropChanged)
    inkPolarity = Property(int, lambda self: self._polarity.value, notify=inkPolarityChanged)

    # ------------------------------------------------------------------------ slots
    @Slot(bool)
    def startStop(self, start: bool) -> None:
        self.start_stop_requested.emit(bool(start))

    @Slot()
    def grabMode(self) -> None:
        self.grab_mode_requested.emit()

    @Slot()
    def toggleGlass(self) -> None:
        self.toggle_glass_requested.emit()

    @Slot()
    def browseModelsDir(self) -> None:
        """Native folder picker (no parent window: ours is a QWindow, not a QWidget)."""
        from PySide6.QtWidgets import QFileDialog

        chosen = QFileDialog.getExistingDirectory(None, "Models directory", self._cfg.models_dir)
        if chosen:
            self._set_config("modelsDir", chosen)

    @Slot()
    @Slot(bool)
    def downloadModel(self, sugoi: bool = False) -> None:
        """Download the Argos package for the selected pair (via English pivot when the source is
        "auto": we download en -> target), or the Sugoi ja -> en model when ``sugoi`` is set."""
        if self._download_active():
            self.show_status("A download is already running.")
            return
        if sugoi:
            src, tgt = "ja", "en"
        else:
            src, tgt = self._cfg.source_lang, self._cfg.target_lang
            if src == "auto":
                src = "en"
            if src == tgt:
                self.show_status("Source and target language are the same.")
                return
        label = download_label(bool(sugoi), src, tgt)
        worker = ModelDownloadWorker(self._cfg.models_dir.strip() or self._cfg.models_dir, src, tgt, self, sugoi=bool(sugoi))
        self._download_worker = worker
        self._download_base_label = label
        self._download_label = f"Downloading {label} model…"
        self._download_progress = -1
        self._download_visible = True
        worker.progress.connect(self._on_download_progress)
        worker.finished_ok.connect(self._on_download_ok)
        worker.failed.connect(self._on_download_failed)
        worker.start()
        self.downloadChanged.emit()

    @Slot()
    def downloadMangaOcr(self) -> None:
        """Fetch the manga-ocr ONNX bundle into the models dir (F3); shares the progress row."""
        if self._download_active():
            self.show_status("A download is already running.")
            return
        worker = MangaOcrDownloadWorker(self._cfg.models_dir.strip() or self._cfg.models_dir, self)
        self._download_worker = worker
        self._download_base_label = "manga-ocr models"
        self._download_label = "Downloading manga-ocr models…"
        self._download_progress = -1
        self._download_visible = True
        worker.progress.connect(self._on_download_progress)
        worker.finished_ok.connect(self._on_manga_ocr_ok)
        worker.failed.connect(self._on_download_failed)
        worker.start()
        self.downloadChanged.emit()

    def _manga_ocr_models_ready(self) -> bool:
        from ..ocr.models import models_ready

        return models_ready(self._cfg.models_dir)

    mangaOcrModelsReady = Property(bool, _manga_ocr_models_ready, notify=downloadChanged)

    @Slot(str)
    def _on_manga_ocr_ok(self, path: str) -> None:
        self._download_visible = False
        self.downloadChanged.emit()
        self.show_status(f"manga-ocr models installed at {path}")
        self.models_changed.emit()

    @Slot()
    def hideDownload(self) -> None:
        """Hide the progress row only; the download keeps running and reports to the status strip."""
        if self._download_visible:
            self._download_visible = False
            self.downloadChanged.emit()

    @Slot(int, int)
    def _on_download_progress(self, done: int, total: int) -> None:
        self._download_label, self._download_progress = download_progress(self._download_base_label, done, total)
        self.downloadChanged.emit()

    @Slot(str)
    def _on_download_ok(self, path: str) -> None:
        self._download_visible = False
        self.downloadChanged.emit()
        self.show_status(f"Installed model at {path}")
        self.models_changed.emit()

    @Slot(str)
    def _on_download_failed(self, message: str) -> None:
        self._download_visible = False
        self.downloadChanged.emit()
        self.show_status(f"Download failed: {message}")

    @Slot(str, str, result=bool)
    def setHotkey(self, which: str, text: str) -> bool:
        """Commit a hotkey field; ``which`` is ``"grab"`` | ``"running"`` | ``"hidden"``.

        Returns True when the (normalized) hotkey was accepted - the field should then display
        the property value.  Empty text returns False silently (the field reverts, no status);
        invalid text returns False with ``Invalid hotkey ...`` in the status strip.
        """
        field = _HOTKEY_FIELDS.get(str(which))
        if field is None:
            self.show_status(f"Unknown hotkey {which!r}")
            return False
        prop = _HOTKEY_PROPS[field]
        text = str(text).strip()
        if not text:
            return False
        try:
            normalized = normalize_hotkey(text)
        except Exception as exc:
            self.show_status(f"Invalid hotkey {text!r}: {exc}")
            return False
        if getattr(self._cfg.hotkeys, field) != normalized:
            setattr(self._cfg.hotkeys, field, normalized)
            self._config_edited()
        getattr(self, prop + "Changed").emit()
        return True

    @Slot()
    def startMove(self) -> None:
        """System move of the window; only valid from a QML ``onPressed`` handler."""
        if self._window is not None:
            self._window.startSystemMove()

    @Slot(int)
    def startResize(self, edges: int) -> None:
        """No-op: the window is fixed-size.  Kept so old/cached QML never crashes calling it."""
        return

    @Slot()
    def keyboardMove(self) -> None:
        """Alt+Space menu "Move": DefWindowProc's keyboard move loop (arrows, Enter / Esc)."""
        if self._window is not None:
            win32.keyboard_move(self._window)

    @Slot()
    def keyboardSize(self) -> None:
        """No-op: the window is fixed-size, so there is no keyboard size loop to start."""
        return

    @Slot()
    def minimize(self) -> None:
        if self._window is not None:
            self._window.showMinimized()

    @Slot()
    def close(self) -> None:
        """Close the window (``closeEvent`` flushes the pending save and emits ``closed``)."""
        if self._window is not None:
            self._window.close()

    @Slot()
    def openLogs(self) -> None:
        """Open the log folder of the packaged build in Explorer."""
        folder = user_data_dir() / "logs"
        if folder.is_dir():
            QDesktopServices.openUrl(QUrl.fromLocalFile(str(folder)))
        else:
            self.show_status(f"No log folder yet ({folder})")


# ------------------------------------------------------------------------------------ window
class ControlWindow(QQuickView):
    """Main settings window; see the module docstring."""

    config_changed = Signal(object)  # AppConfig
    start_stop_requested = Signal(bool)  # True = start
    grab_mode_requested = Signal()
    toggle_glass_requested = Signal()
    capture_mode_requested = Signal(bool)  # overlay capture mode on/off
    models_changed = Signal()  # a package was downloaded
    closed = Signal()  # the user closed the window
    _frame_ready = Signal(object)  # BackdropFrame, emitted from the grabber thread (queued)

    def __init__(
        self,
        cfg: AppConfig,
        config_path: Optional[Path] = None,
        parent: Optional[QWindow] = None,
    ) -> None:
        super().__init__(parent)
        self.setTitle(WINDOW_TITLE)
        self.setFlags(WINDOW_FLAGS)
        self.setColor(Qt.GlobalColor.transparent)
        self.setResizeMode(QQuickView.ResizeMode.SizeRootObjectToView)
        self.setMinimumSize(WINDOW_DEFAULT_SIZE)
        self.setMaximumSize(WINDOW_DEFAULT_SIZE)
        self.resize(WINDOW_DEFAULT_SIZE)
        if RESOURCES_OK:
            self.setIcon(QIcon(":/icons/app.png"))

        self.appearance = Appearance(self)
        self.bridge = ControlBridge(cfg, config_path, window=self, appearance=self.appearance, parent=self)
        for name in ("config_changed", "start_stop_requested", "grab_mode_requested", "toggle_glass_requested",
                     "capture_mode_requested", "models_changed"):
            getattr(self.bridge, name).connect(getattr(self, name))

        self._provider = BackdropProvider()
        self.engine().addImageProvider("backdrop", self._provider)
        self.qml_warnings: List[str] = []
        self.engine().warnings.connect(self._on_qml_warnings)
        context = self.rootContext()
        context.setContextProperty("bridge", self.bridge)
        context.setContextProperty("appearance", self.appearance)

        self._geometry = WindowGeometry()
        self._grabber: Optional[BackdropGrabber] = None
        self._close_seen = False
        self._frame_ready.connect(self._on_backdrop_frame)
        self.windowStateChanged.connect(self._on_window_state_changed)
        self.screenChanged.connect(self._on_screen_changed)
        self.appearance.changed.connect(self._update_grabber)

        self.setSource(QUrl(MAIN_QML_URL))
        if self.status() == QQuickView.Status.Error:
            for err in self.errors():
                log.error("QML: %s", err.toString())
        elif self.rootObject() is None:
            log.error("QML root object missing (status %s)", self.status())
        if profile.profiler.enabled:
            self._install_profile_hooks()

    def _install_profile_hooks(self) -> None:
        """``GLASSTRANSLATE_PROFILE`` only: count swaps and tab switches (F2-0, never on by default)."""
        prof = profile.profiler
        # frameSwapped is emitted on the render thread.  A direct Python slot there needs the GIL
        # while the GUI thread may hold it inside C++ (exposeEvent -> render-loop sync waiting for
        # that same render thread) -> deadlock on the first frame.  Queue it: counts stay exact,
        # the timestamp becomes GUI-dispatch time (documented in profile.py).
        self._profile_hooks: List[Any] = [
            self.frameSwapped.connect(lambda: prof.mark("swap"), Qt.ConnectionType.QueuedConnection)
        ]
        tab = self.rootObject().findChild(QQuickItem, "tabBar") if self.rootObject() is not None else None
        if tab is not None:
            self._profile_hooks.append(tab.currentIndexChanged.connect(lambda: prof.mark("tab", index=tab.property("currentIndex"))))

    # ---------------------------------------------------------------- public
    @property
    def config(self) -> AppConfig:
        return self.bridge.config

    @property
    def status_history(self) -> List[str]:
        """Every ``show_status`` message so far (smoke report)."""
        return self.bridge.status_history

    @property
    def grabber(self) -> Optional[BackdropGrabber]:
        return self._grabber

    def load_config(self, cfg: AppConfig) -> None:
        """Populate every control from ``cfg`` without emitting changes."""
        self.bridge.load_config(cfg)

    def set_running(self, running: bool) -> None:
        """Reflect the pipeline state on the Start/Stop button and the running dot."""
        self.bridge.set_running(running)

    @Slot(object)
    def update_stats(self, stats: PipelineStats) -> None:
        """Refresh the latency readout from a pipeline pass."""
        if isinstance(stats, PipelineStats):
            self.bridge.stats.update(stats)

    @Slot(str)
    def show_status(self, message: str) -> None:
        self.bridge.show_status(message)

    def save_soon(self) -> None:
        """Schedule a debounced save (for changes made outside this window,
        e.g. the glass geometry)."""
        self.bridge.save_soon()

    @Slot()
    def save_now(self) -> None:
        """Persist the config immediately (normally driven by the debounce timer)."""
        self.bridge.save_now()

    # ---------------------------------------------------------------- events
    def showEvent(self, event: QShowEvent) -> None:
        super().showEvent(event)
        win32.exclude_from_capture(self)
        self._refresh_geometry()
        self._update_grabber()

    def hideEvent(self, event: QHideEvent) -> None:
        super().hideEvent(event)
        self._update_grabber()

    def exposeEvent(self, event: QExposeEvent) -> None:
        super().exposeEvent(event)
        if self.isExposed():
            self._refresh_geometry()
            self._poke()

    def moveEvent(self, event: QMoveEvent) -> None:
        super().moveEvent(event)
        self._refresh_geometry()
        rect = self._geometry.get()[0]
        profile.profiler.geometry("move", rect)
        if rect is not None:
            self.bridge.set_window_origin(rect.x, rect.y)
        self._poke()

    def resizeEvent(self, event: QResizeEvent) -> None:
        super().resizeEvent(event)
        self._refresh_geometry()
        self._poke()

    def close(self) -> bool:
        """Close the window; flushes the pending save and emits ``closed``.

        ``QWindow.close()`` returns True *without* delivering ``closeEvent`` when the window has
        no platform window yet (never shown, e.g. offscreen tests), so that case is handled here.
        """
        self._close_seen = False
        ok = super().close()
        if ok and not self._close_seen:
            self._on_close()
        return ok

    def closeEvent(self, event: QCloseEvent) -> None:
        super().closeEvent(event)
        if event.isAccepted():
            self._close_seen = True
            self._on_close()

    def _on_close(self) -> None:
        self.bridge.flush_pending_save()
        self.shutdown()
        self.closed.emit()

    # -------------------------------------------------------------- backdrop
    def shutdown(self) -> None:
        """Stop the grabber thread and the appearance watcher (idempotent).

        Called from ``closeEvent`` and by the application before the ``QApplication`` is
        destroyed, so no thread or native event filter outlives the Qt objects it touches.
        """
        self.stop_grabber()
        self.appearance.stop()

    def stop_grabber(self, timeout_s: float = 1.0) -> None:
        """Stop and join the grabber thread (idempotent)."""
        grabber, self._grabber = self._grabber, None
        if grabber is not None:
            grabber.stop()
            grabber.join(timeout_s)

    def _refresh_geometry(self) -> None:
        if not self.isVisible():
            return
        self._geometry.update(win32.physical_rect(self), self.devicePixelRatio())

    def _update_grabber(self) -> None:
        minimized = bool(self.windowStates() & Qt.WindowState.WindowMinimized)
        active = self.isVisible() and not minimized and self.appearance.glassAllowed
        if active:
            if self._grabber is None:
                self._grabber = BackdropGrabber(self._geometry, self._frame_ready.emit)
                self._grabber.start()
            self._grabber.resume()
        elif self._grabber is not None:
            self._grabber.pause()

    def _poke(self) -> None:
        if self._grabber is not None and not self._grabber.paused:
            profile.profiler.mark("poke")
            self._grabber.poke()

    @Slot(object)
    def _on_backdrop_frame(self, frame: object) -> None:
        if not isinstance(frame, BackdropFrame):
            return
        profile.profiler.frame_gui(frame, lambda: win32.physical_rect(self))
        self._provider.set_image(frame.image)
        profile.profiler.timed_call("push_backdrop_ms", self.bridge.push_backdrop, frame)

    @Slot(Qt.WindowState)
    def _on_window_state_changed(self, _state: Qt.WindowState) -> None:
        self._update_grabber()

    @Slot(QScreen)
    def _on_screen_changed(self, _screen: QScreen) -> None:
        self._refresh_geometry()
        self._poke()

    @Slot(list)
    def _on_qml_warnings(self, warnings: list) -> None:
        for warning in warnings:
            text = warning.toString() if hasattr(warning, "toString") else str(warning)
            self.qml_warnings.append(text)
            log.warning("QML: %s", text)
