"""Compiled Qt resources guard for the control window (split out of ``ui/control.py``).

``RESOURCES_OK`` is evaluated once at import time; see :func:`_ensure_resources`.
"""
from __future__ import annotations

import importlib
import logging
import sys

from ..config.settings import project_root
from .bridge_fields import is_frozen

__all__ = ["RESOURCES_OK", "_ensure_resources"]

log = logging.getLogger(__name__)


# ------------------------------------------------------------------------------- resources
def _ensure_resources() -> bool:
    """Import the compiled Qt resources (``:/qml``, ``:/fonts``, ``:/icons``).

    ``resources_rc.py`` is generated by ``tools/build_resources.py`` and not committed during
    development; in a source checkout it is built once here when missing, and rebuilt when
    present but stale (its digest no longer matches its QML/shader/font inputs) so an outdated
    file left over from before a redesign can never be served silently.  The frozen exe must ship
    a fresh one; there is no ``tools/`` there to rebuild from.
    """
    try:
        module = importlib.import_module("glasstranslate.ui.resources_rc")
        imported = True
    except ImportError:
        module = None
        imported = False

    if is_frozen():
        if imported:
            return True
        log.error("resources_rc is missing from the frozen bundle; QML, fonts and icon are unavailable")
        return False

    root = str(project_root())
    if root not in sys.path:
        sys.path.insert(0, root)
    try:
        from tools.build_resources import build, check_digest  # noqa: WPS433 - dev-only dependency
    except ImportError:
        # pip-installed layout without tools/: nothing to rebuild from, fall back to the import result.
        return imported

    if imported and check_digest()[0]:
        return True
    if imported:
        log.warning("resources_rc.py is stale (inputs changed since it was generated); rebuilding")
    try:
        out = build()
        importlib.invalidate_caches()
        if imported:
            # Unregister the old byte buffers before reload overwrites the module
            # globals that keep them alive; Qt would otherwise hold dangling data.
            module.qCleanupResources()
            importlib.reload(module)
        else:
            importlib.import_module("glasstranslate.ui.resources_rc")
        log.info("built Qt resources: %s", out)
        return True
    except Exception:
        log.exception("building the Qt resources failed; the control window cannot load its QML")
        return False


RESOURCES_OK = _ensure_resources()
